In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [57]:
df = pd.read_csv("seattle-weather.csv")

In [58]:
df

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [59]:
df = df.drop("date", axis = "columns")
df.head()

precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7  drizzle
1           10.9      10.6       2.8   4.5     rain
2            0.8      11.7       7.2   2.3     rain
3           20.3      12.2       5.6   4.7     rain
4            1.3       8.9       2.8   6.1     rain

In [60]:
from sklearn.preprocessing import MinMaxScaler

In [61]:
scaler = MinMaxScaler() #Posso usar Pipeline ou Standart
scaler.fit(df[["precipitation"]])
df["precipitation"] = scaler.transform(df[["precipitation"]])

scaler.fit(df[["temp_max"]])
df["temp_max"] = scaler.transform(df[["temp_max"]])

scaler.fit(df[["temp_min"]])
df["temp_min"] = scaler.transform(df[["temp_min"]])

scaler.fit(df[["wind"]])
df["wind"] = scaler.transform(df[["wind"]])

df

precipitation  temp_max  temp_min      wind  weather
0          0.000000  0.387097  0.476378  0.472527  drizzle
1          0.194991  0.327957  0.389764  0.450549     rain
2          0.014311  0.357527  0.562992  0.208791     rain
3          0.363148  0.370968  0.500000  0.472527     rain
4          0.023256  0.282258  0.389764  0.626374     rain
...             ...       ...       ...       ...      ...
1456       0.153846  0.161290  0.346457  0.274725     rain
1457       0.026834  0.177419  0.346457  0.098901     rain
1458       0.000000  0.236559  0.303150  0.241758      fog
1459       0.000000  0.193548  0.240157  0.329670      sun
1460       0.000000  0.193548  0.196850  0.340659      sun

[1461 rows x 5 columns]

In [62]:
from sklearn.preprocessing import LabelEncoder
Numerics = LabelEncoder()
df["weather_num"] = Numerics.fit_transform(df["weather"])
df.head()

precipitation  temp_max  temp_min      wind  weather  weather_num
0       0.000000  0.387097  0.476378  0.472527  drizzle            0
1       0.194991  0.327957  0.389764  0.450549     rain            2
2       0.014311  0.357527  0.562992  0.208791     rain            2
3       0.363148  0.370968  0.500000  0.472527     rain            2
4       0.023256  0.282258  0.389764  0.626374     rain            2

In [63]:
df["weather_num"].unique()

array([0, 2, 4, 3, 1])

In [64]:
df["weather"].unique()

array(['drizzle', 'rain', 'sun', 'snow', 'fog'], dtype=object)

In [65]:
df = df.drop("weather", axis="columns")
df.head()

precipitation  temp_max  temp_min      wind  weather_num
0       0.000000  0.387097  0.476378  0.472527            0
1       0.194991  0.327957  0.389764  0.450549            2
2       0.014311  0.357527  0.562992  0.208791            2
3       0.363148  0.370968  0.500000  0.472527            2
4       0.023256  0.282258  0.389764  0.626374            2

In [66]:
X= df.drop("weather_num", axis="columns")

In [67]:
y= df["weather_num"]

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42) 

In [69]:
dtree_model = DecisionTreeClassifier(max_depth = 3).fit(X_train, y_train) 

In [70]:
dtree_predictions = dtree_model.predict(X_test) 

In [71]:
dtree_predictions

array([4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 2, 4, 4, 4, 4, 2, 4, 4, 3, 4, 2, 2, 2, 2, 4, 2, 4, 4, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 4, 2, 4, 2, 2, 4, 2, 4, 2, 4, 2, 4, 4, 4,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 4, 2, 4, 4, 2,
       4, 2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2,
       2, 4, 2, 2, 0, 0, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4,
       2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 2,
       4, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2,
       2, 2, 2, 4, 4, 2, 4, 2, 2, 4, 3, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 4, 2, 4, 2, 4, 3, 4, 2, 4, 4, 2, 4, 4, 4, 4, 4, 2, 2,
       4, 3, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2,
       4, 4, 2, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 4, 4, 4, 4,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 2,

In [72]:
cm = confusion_matrix(y_test, dtree_predictions) 
cm

array([[  1,   0,   0,   0,  10],
       [  1,   0,   0,   0,  29],
       [  0,   0, 149,   2,  10],
       [  0,   0,   6,   2,   0],
       [  0,   0,   0,   0, 156]], dtype=int64)

In [73]:
from sklearn.metrics import accuracy_score

In [74]:
accuracy_score(y_test, dtree_predictions)

0.8415300546448088

In [75]:
#Usando outro aprendizado
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(X_train, y_train)

In [76]:
y_pred = gnb.predict(X_test)

In [77]:
y_pred

array([4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 4, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 4, 2, 4, 2, 2, 4, 2, 4, 2, 4, 2, 4, 4, 4,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 4, 2, 3, 2, 4, 2, 4, 2, 4, 4, 2,
       4, 2, 2, 4, 4, 2, 3, 4, 4, 2, 4, 2, 4, 4, 2, 3, 2, 4, 4, 2, 4, 2,
       2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4,
       2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 2,
       4, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2,
       3, 2, 2, 4, 4, 2, 4, 2, 2, 4, 3, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4,
       2, 0, 4, 4, 4, 2, 4, 2, 4, 3, 4, 2, 4, 4, 2, 4, 4, 4, 4, 4, 2, 2,
       4, 3, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2,
       4, 4, 2, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 4, 4, 4, 4,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 2,

In [78]:
accuracy_score(y_test, y_pred)

0.8360655737704918

In [79]:
# Outro
from sklearn.svm import SVC 
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 

In [80]:
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, y_test)
accuracy

0.73224043715847

In [81]:
# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions)
cm

array([[  0,   0,   2,   0,   9],
       [  0,   0,   6,   0,  24],
       [  0,   0, 129,   0,  32],
       [  0,   0,   8,   0,   0],
       [  0,   0,  17,   0, 139]], dtype=int64)

In [82]:
#Usando o perceptron como Rede Neural
from sklearn.datasets import make_classification
from sklearn.linear_model import Perceptron
from sklearn.ensemble import BaggingClassifier

In [83]:
#Declarando o perceptron
perceptron_model = Perceptron(random_state=42)

In [84]:
#Existem aparentemente 2 formas de fazer ensemble o Bagging e o Boosting, vamos usar o bagging
ensemble_model = BaggingClassifier(base_estimator=perceptron_model, n_estimators=5, random_state=42)

In [85]:
#Realizando o treino
ensemble_model.fit(X_train, y_train)

C:\Users\Veecstart\Desktop\weather-project\ambiente\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=Perceptron(random_state=42), n_estimators=5,
                  random_state=42)

In [86]:
#Verificar a predição
predictions = ensemble_model.predict(X_test)
predictions

array([4, 2, 2, 4, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4, 4, 2, 4,
       2, 2, 4, 2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 4,
       2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 4, 2, 4, 2, 4, 2, 2, 4, 4,
       2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2,
       4, 2, 2, 4, 4, 2, 2, 4, 4, 4, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4,
       2, 2, 4, 4, 4, 2, 4, 4, 2, 4, 4, 2, 2, 4, 2, 4, 2, 2, 4, 4, 2, 2,
       4, 4, 4, 2, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 4, 4, 2, 4, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 4, 2, 4, 2, 4, 2, 4, 2, 4, 4, 2, 4, 4, 2, 2, 4, 2, 2,
       4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 2, 2, 4, 4, 4,
       2, 2, 2, 4, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 4, 4, 2, 4, 2, 4, 4,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 2, 2, 4, 4,

In [87]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.7568306010928961

In [93]:
# Usando agora um boosting como exemplo (Com o mesmo perceptron)
from sklearn.ensemble import AdaBoostClassifier
#Adaboosting precisa de um weak classifier para ter probabilidades de suporte - Vamos usar a decision tree
# dtree_model e dtree_predictions já existem

In [97]:
#Como ja temos o classificador fraco usando decision tree basta reutilizar
# instanciar o modelo AdaBoost
boosting = AdaBoostClassifier(base_estimator=dtree_model, n_estimators=50, algorithm='SAMME.R', random_state=42)

In [99]:
#Treinando o modelo
boosting.fit(X_train, y_train)

C:\Users\Veecstart\Desktop\weather-project\ambiente\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=3),
                   random_state=42)

In [101]:
#previsão
prev = boosting.predict(X_test)
prev

array([1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 4, 2, 0, 4, 2, 2, 4, 1, 4, 2, 4,
       2, 4, 1, 2, 2, 2, 4, 1, 2, 1, 1, 3, 0, 2, 2, 2, 2, 1, 2, 4, 4, 1,
       4, 2, 2, 1, 2, 0, 1, 2, 1, 2, 4, 2, 2, 1, 2, 1, 2, 1, 2, 4, 1, 4,
       2, 1, 2, 2, 2, 1, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 2, 1, 2, 4, 1, 2,
       2, 2, 2, 1, 1, 2, 2, 4, 4, 2, 1, 2, 1, 2, 3, 3, 2, 4, 4, 2, 1, 2,
       2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 1, 4, 1, 0, 1,
       1, 1, 4, 1, 2, 2, 2, 4, 1, 1, 2, 2, 4, 1, 4, 2, 1, 1, 2, 1, 1, 1,
       2, 2, 1, 1, 2, 2, 4, 4, 2, 4, 0, 2, 2, 0, 4, 4, 2, 2, 0, 4, 2, 2,
       1, 4, 4, 2, 4, 0, 0, 2, 2, 4, 2, 2, 4, 4, 4, 4, 1, 2, 0, 1, 4, 2,
       2, 2, 2, 4, 0, 2, 4, 2, 2, 1, 3, 1, 2, 4, 4, 4, 0, 1, 4, 1, 2, 4,
       2, 4, 4, 0, 2, 2, 1, 2, 4, 3, 4, 2, 1, 1, 2, 2, 4, 4, 1, 1, 3, 2,
       1, 2, 4, 4, 4, 4, 3, 2, 2, 2, 2, 4, 1, 4, 2, 1, 2, 2, 2, 2, 1, 2,
       4, 2, 2, 1, 4, 4, 4, 4, 1, 2, 4, 1, 2, 2, 1, 4, 4, 2, 1, 4, 1, 1,
       2, 1, 1, 2, 1, 2, 4, 4, 2, 2, 4, 2, 2, 2, 2,

In [102]:
accuracy = accuracy_score(y_test, predictions)
accuracy

0.7568306010928961